### ISSUE TITLE
Is there no `onCopy` event?

### ISSUE THREAD

**Issue by i-am-the-slime** [lumihq/purescript-react-basic#104]
I'm going through some events and I couldn't find this one for `p` for example.

**Comment by i-am-the-slime** [comment]
I think there's actually a few more. Is this because these events are not high priority or is there some technical limitation?

**Comment by spicydonuts** [comment]
It's just that adding event props is a manual process and no one has needed this even yet. Event PRs are always welcome.

**Comment by i-am-the-slime** [comment]
I made a PR with the events I could make work with react-testing-library.

**Comment by spicydonuts** [comment]
Fixed by #105
