### ISSUE TITLE
data attributes missing from some elements

### ISSUE THREAD

**Issue by FruitieX** [lumihq/purescript-react-basic#106]
Hi,

I can see that https://github.com/lumihq/purescript-react-basic/issues/89 was resolved and the `_data` prop works fine, great! However, it seems like the `_data` prop is missing on a few elements as is evident in [React/Basic/DOM/Generated.purs](https://github.com/lumihq/purescript-react-basic/blob/master/src/React/Basic/DOM/Generated.purs#L5566) (for example Props_input).

There's a few other elements with missing `_data` prop as well. Seems like this was omitted by mistake?

**Comment by FruitieX** [comment]
hmm seems to be caused by this: https://github.com/lumihq/purescript-react-basic/blob/master/codegen/index.js#L103

We should probably add `["_data"]` prop to the `noChildren` case

**Comment by spicydonuts** [comment]
I'll try to get to this soon.
