### ISSUE TITLE
Props_form contains onSubmit field two times

### ISSUE THREAD

**Issue by srghma** [lumihq/purescript-react-basic#112]
https://github.com/lumihq/purescript-react-basic/blob/feee3a51a531f65ff0c0802bffa77e9cd0bd0164/src/React/Basic/DOM/Generated.purs#L5726-L5727

**Comment by srghma** [comment]
and onInvalid

https://github.com/lumihq/purescript-react-basic/blob/feee3a51a531f65ff0c0802bffa77e9cd0bd0164/src/React/Basic/DOM/Generated.purs#L5703-L5704

**Comment by srghma** [comment]
why `Props_h3` (and other non-form elements) has `onSubmit` field?

**Comment by spicydonuts** [comment]
I think all the elements get the event handlers because events can be captured in parents as they bubble up. The duplicates probably mean those elements have some events defined explicitly even though they already inherit them from the global/shared list.

**Comment by srghma** [comment]
Ok, it's not a problem that they are duplicated
