### ISSUE TITLE
Support aria prefixed attributes

### ISSUE THREAD

**Issue by i-am-the-slime** [lumihq/purescript-react-basic#115]
This might be similar to #89 but maybe the set of possible aria attributes is actually limited. I don't know. However supporting them via _aria and a homogeneous object could be a start. What do you think?

**Comment by spicydonuts** [comment]
Definitely! We have some accessibility tasks backlogged but I don't know when we'll get to them. Adding them all explicitly seems preferable if that's an option.

**Comment by spicydonuts** [comment]
I added basic aria- support using `_aria :: Object String` (same as `_data`) here: https://github.com/lumihq/purescript-react-basic-dom

Haven't tagged a release yet but I will very soon.
