### ISSUE TITLE
Is it feasible to handle required fields?

### ISSUE THREAD

**Issue by paluh** [lumihq/purescript-react-basic#122]
Hi,

Thanks for building and maintaining this library. I really like it :-)

I have a question somewhat related to our effort in the  _react-basic-mui_ project about possible handling of required props.
Is it possible with the current strategy of the codegen to introduce a separation between required and optional props rows? I'm asking because I'm not sure what is the original source of the type information used by the codegen.

 I think that in general we could preserve the current API but increase safety a bit with something like:

``` purescript
type PropsRequired_a r = ( ... | r ) 
type PropsOptional_a = ( ... )

type Props_a = PropsRequired_a PropsOptional_a

a
  :: forall attrs attrs_
   . Union attrs attrs_ PropsOptional_a
  => Record (PropsRequired_a attrs)
  -> JSX
a = element a'
```

**Comment by spicydonuts** [comment]
Yeah, it's definitely possible. Mainly it's just a lot of work to define all these types.

The existing types are here: https://github.com/lumihq/purescript-react-basic/blob/main/codegen/react-html-attributes.json
And they're used to generate the DOM module here: https://github.com/lumihq/purescript-react-basic/blob/main/codegen/index.js

**Comment by paluh** [comment]
Hi @spicydonuts!

Thanks a lot for the response. Could you please tell me a bit more about the codegen process - how do you build a react-html-attributes.json file exactly (sorry if this is naive question ;-))?

**Comment by spicydonuts** [comment]
The file was extracted from the npm package `react-html-attributes`. We created our own copy because we had a lot of overrides to make. You can run the codegen (react-html-attributes.json -> src/React/Basic/DOM/Generated.purs) using `cd codegen; npm i; node .`.

**Comment by paluh** [comment]
It seems that react-html-attributes is missing type info so it won't help in this case. I think I'm going to close this for now till I find time to experiment with typescript definitions through read-dts. Thanks!
