### ISSUE TITLE
Dead 'docs' link

### ISSUE THREAD

**Issue by andys8** [lumihq/purescript-react-basic#126]
The `docs` link refers to https://react-basic-starter.github.io

![Screenshot_20200715-121134~2](https://user-images.githubusercontent.com/13085980/87533148-79413f00-c694-11ea-9795-e2db0b9ab497.jpg)

This is currently dead. The docs also say that it's WIP. If there are no docs at all, I'd suggest removing the link for now. If there are docs, I'd add fix the links (even if WIP) instead.

**Comment by paluh** [comment]
Do we want to drop the second sentence from the paragraph with the dead link for now? Should I provide such a PR?

**Comment by andys8** [comment]
Same with https://github.com/spicydonuts/purescript-react-basic-hooks

**Comment by spicydonuts** [comment]
Sorry, I'm not sure when we'll get to this. It's definitely something that needs to be done, but we haven't been able to set aside the time for it yet. In the meantime I've updated the readme to be a little more helpful than a dead link.
