### ISSUE TITLE
Docs: toReactComponent doesn't exist (anymore)

### ISSUE THREAD

**Issue by andys8** [lumihq/purescript-react-basic#129]
There is a reference to `toReactComponent`. It doesn't exist anymore. Not sure by what it was replaced ;)

https://github.com/lumihq/purescript-react-basic/blob/3569fea76dcd776baceda071a6f6286befb92142/src/React/Basic.purs#L70

**Comment by spicydonuts** [comment]
It's over here now: https://github.com/lumihq/purescript-react-basic-classic/blob/main/src/React/Basic/Classic.purs#L280

**Comment by andys8** [comment]
Ah, thank you very much.

I was looking at `react-basic-hooks` where `ReactComponent` is reedported.:

https://pursuit.purescript.org/packages/purescript-react-basic-hooks/6.1.0/docs/React.Basic.Hooks#t:ReactComponent

What I actually needed/wanted is [`reactComponent`](https://pursuit.purescript.org/packages/purescript-react-basic-hooks/6.1.0/docs/React.Basic.Hooks#t:ReactComponent) and it took me some time to figure out, I had run the effect to be able to import and use it JavaScript land :)

So, I'm looking forward to docs. The library is looking pretty neat :)

**Comment by andys8** [comment]
I guess the docs are fine then.

**Comment by spicydonuts** [comment]
Ahh, yes, that could probably be clearer. Planning to have some JS React component interop examples in the shared documentation soon.
