### ISSUE TITLE
React element Refs

### ISSUE THREAD

**Issue by justinwoo** [lumihq/purescript-react-basic#13]
It would be good to be able to work with the normal React component refs on elements, since those are quite useful for cases like mounting charting libraries, playing/pausing audio elements, etc.

**Comment by paf31** [comment]
What about wrapping those on the JS side and then bringing them in using the FFI?

I think I'd prefer to have a well-understood subset of functionality here, and we had enough problems with refs in `purescript-react` before that I'd rather exclude them if they're only used in a small number of cases.

**Comment by justinwoo** [comment]
You mean wrapping whole components that use refs? I'd really not want to.

I use refs fairly frequently in my own code though, but not exposing refs directly and providing a StrMap bound on the instance would be nicer than trying to expose the guts of it.

**Comment by paf31** [comment]
> You mean wrapping whole components that use refs? I'd really not want to.

I mean encapsulating whatever state needs refs in one React component, and then using that from other components which are defined using this library.

**Comment by spicydonuts** [comment]
Just ran into this.. it'd be a shame to build a whole FFI component for one line of code, but I'm not sure how to fit this into the building blocks we have.

```purs
input = react
  { displayName: "Input"
  , initialState: { indeterminate: false }
  , receiveProps: \props state setState ->
      when $ props.indeterminate /= state.indeterminate do
        setState \_ -> { indeterminate: props.indeterminate }
        -- inputNode <- // ReactDOM.findDOMNode(this)
        setIndeterminate props.indeterminate inputNode
  , render
  }
```

**Comment by spicydonuts** [comment]
Added a `Ref` component to our internal library. Might make sense to move it here or another library of utility components, but here it is since I'm not sure when we'll get to that.

https://gist.github.com/spicydonuts/12725096894c8d95431cf0608a5b5b31

**Comment by spicydonuts** [comment]
In addition to the pattern above, you can also access a the dom node at the root level of your component using the v2 API:

```purs
import React.Basic.DOM (findDOMNode)

...
  receiveProps { instance_ } = do
    rootNode <- findDOMNode instance_
```
