### ISSUE TITLE
Component-launching helper functions in React.Basic.Util

### ISSUE THREAD

**Issue by milesfrain** [lumihq/purescript-react-basic#131]
Proposing that we add a `renderInRoot` helper function to make this common pattern easier:
```purs
import React.Basic.Util (renderInRoot)

myComponent :: Component {}
myComponent = do
  component "MyComponentName" \_ -> React.do
    -- ...

main :: Effect Unit 
main = renderInRoot $ myComponent {}
```

A slightly more verbose option is:
```purs
import React.Basic.Util (createRootElement)

mkMyComponent :: Component {}
mkMyComponent = do
  component "MyComponentName" \_ -> React.do
    -- ...

main :: Effect Unit 
main = do
  root <- createRootElement
  myComponent <- mkMyComponent
  render (myComponent {}) root
```

We could support both options, and reuse `createRootElement` in `renderInRoot`.

For context, Halogen has some convenient helper functions for launching components, such as `awaitBody` in [Halogen.Aff.Util](
https://github.com/purescript-halogen/purescript-halogen/blob/master/src/Halogen/Aff/Util.purs):

```purs
hookComponent = Hooks.component \_ _ -> Hooks.do
  -- ...

main :: Effect Unit
main =
  HA.runHalogenAff do
    body <- HA.awaitBody
    void $ runUI hookComponent Nothing body
```

**Comment by spicydonuts** [comment]
@milesfrain Can you move this to [purescript-react-basic-dom](https://github.com/lumihq/purescript-react-basic-dom)?

**Comment by milesfrain** [comment]
Created https://github.com/lumihq/purescript-react-basic-dom/issues/8
