### ISSUE TITLE
Link to react-basic docs is 404

### ISSUE THREAD

**Issue by pmiddend** [lumihq/purescript-react-basic#132]
To "reproduce":

- visit https://pursuit.purescript.org/packages/purescript-react-basic-hooks/6.1.1
- click on link that says "For more info and guides, see the React Basic docs!".

Doesn't give a good first impression for this library and should be fixed, imo. :)

**Comment by spicydonuts** [comment]
This is a dupe of #126. There's more info which notes the dead link in the [current readme](https://github.com/lumihq/purescript-react-basic#purescript-react-basic).
