### ISSUE TITLE
The "children" API

### ISSUE THREAD

**Issue by spicydonuts** [lumihq/purescript-react-basic#14]
I was fixing up `createElement_` and adding a `keyed` helper to stop all the warnings React emits when you use nested arrays as children and stumbled into, "But what if they specify children as props.children??".

Some background:
1. The only thing that makes the "children" prop special is that the dom components (when the first arg to `React.createElement` is a string) use that prop to render child nodes.
1. As a result, JSX has special syntax for children (things between the tags)..
1. And `React.createElement` itself has a special case for any additional props after the first two: they get merged into the children prop

For example,
```jsx
<div>
  {a}
  {b}
</div>
```
and
```js
createElement("div", { children: [a, b] })
```
and
```js
createElement("div", {}, a, b)
```
are all the same.  This is different and produces the "key" warning:
```js
createElement("div", {}, [a, b])
```
(^-- this is how it's currently done in purescript-react-basic)

Looking into this I stumbled onto this discussion: https://github.com/facebook/react/issues/4694

All the reasons for supporting these slightly different APIs are related to JS and JSX convenience and backwards compatability.  Since none of those things matter in `purescript-react-basic` (backwards compatibility does a bit, but it's still young and pre-stable release), I'm going to propose removing the 3rd "children" arg from all of the `React.Basic.DOM` components and adding `children :: JSX` to the prop records of the components which support children.

Thoughts?

**Comment by spicydonuts** [comment]
One more note, in addition to simplifying the external API (where children go), the would also simplify the internal API, as a few FFI functions could be deleted and the DOM module can be built using `component` (using an internal helper which coerces `String` to `ReactComponent props`).

**Comment by paf31** [comment]
👍 Moving `children` into props sounds good to me. We already use `children` as a prop in some places.
