### ISSUE TITLE
What is the correct way to HTML Symbols?

### ISSUE THREAD

**Issue by codingedgar** [lumihq/purescript-react-basic#149]
Thank you so much for this library, and sorry for bothering, I don't seem to find a way to do this

```
<p>I will display &larr;</p>
<p>I will display &#8592;</p>
<p>I will display &#x2190;</p>
```

when I use `DOM.text "&#8592;"` it gets sanitized as `&amp#8592;`, for react it would be something like:

```tsx
<p>I will display {&#x2190;}</p>
```

but I also don't know how to do `{}`

Tried with `DOM.unsafeCreateDOMComponent "&#8593;" >>=  React.element` but it needs an actual component like `p` and I just want to write `"&#8593;"` escaped.

What is the correct way to do it?

**Comment by ptrfrncsmrph** [comment]
You should be able to do
```haskell
R.text "I will display \x2190"
```
https://try.purescript.org/?gist=852f261fb3aefbf9f41d17c6a2ef4af8

**Comment by codingedgar** [comment]
Thank you so much!
