### ISSUE TITLE
Add SyntheticEvent utilities

### ISSUE THREAD

**Issue by spicydonuts** [lumihq/purescript-react-basic#21]
- targetValue
- bubbles
- cancelable
- currentTarget
- defaultPrevented
- eventPhase
- isTrusted
- nativeEvent
- preventDefault
- isDefaultPrevented
- stopPropagation
- isPropagationStopped
- target
- timeStamp
- type

**Comment by paf31** [comment]
API sketch:

```purescript
data EventFn a b = EventFn (a -> b)

instance Category EventFn

preventDefault :: EventFn SyntheticEvent SyntheticEvent
stopPropagation :: EventFn SyntheticEvent SyntheticEvent  

targetValue :: EventFn SyntheticEvent String
targetChecked :: EventFn SyntheticEvent String
```

Crucially, we don't export the EventFn data constructor, or any instances which let real functions creep in.

The functions for a symmetric monoidal category could be defined if we want to support extracting multiple things, or we could do something fancy with `RowToList` like

```purescript
-- Insert RowToList magic here
smoosh 
  :: { foo :: EventFn a foo, bar :: EventFn a bar, ... }
  -> EventFn a { foo :: foo, bar :: bar, ... }
```

Then you could do stuff like

```purescript
preventDefault >>> smoosh { value: targetValue, timeStamp: timeStamp }
```

and extract the value and timestamp at the same time.
