### ISSUE TITLE
Support for ReactDOMServer

### ISSUE THREAD

**Issue by starper** [lumihq/purescript-react-basic#63]
It would be nice to have support for [ReactDOMServer](https://reactjs.org/docs/react-dom-server.html), this way `purescript-react-basic` could be used for server side rendering.

**Comment by starper** [comment]
I'm currently forced to use BuckleScript and, sadly, have very little free time, so PR will have to wait. You can close this issue for now if you want and I'll reopen it when I'll have time to make a PR.

**Comment by shinzui** [comment]
Should this issue be closed since lumihq/purescript-react-basic-dom#6 was merged?

**Comment by spicydonuts** [comment]
Yes, probably, thanks
