### ISSUE TITLE
Support for onKeyDown, etc. in input text?

### ISSUE THREAD

**Issue by tesujimath** [lumihq/purescript-react-basic#76]
I see the original purescript-react supports properties like onKeyDown, which are useful for handling Enter or Escape in text inputs, and that these are not supported in purescript-react-basic.

Is there a plan to support them at some stage?

**Comment by tesujimath** [comment]
Awaiting https://github.com/jackyho112/react-html-attributes/issues/14

**Comment by justinwoo** [comment]
Might also be good just to use the commit SHA?

**Comment by spicydonuts** [comment]
Yep, ideally they'd all be supported correctly. CSS too. It's just a lot of work to find them all :slightly_smiling_face:

**Comment by tesujimath** [comment]
Also requires #83, since adding them upstream is not enough.
