### ISSUE TITLE
Effects inside components

### ISSUE THREAD

**Issue by justinwoo** [lumihq/purescript-react-basic#9]
Is the idea behind the ReactFX effect type that you should only be calling setState and other "non-leaky" effects? I put together an example of using a file input to feed into audio, but of course, it ends up with unsafeCoerceEff everywhere:

https://github.com/justinwoo/react-basic-thing/blob/2bea8435b836f9a202e2df534296b8e8cc09c1d9/src/Main.purs#L36-L55

I'm personally pretty okay with just putting this everywhere to the typical messy React components that are everywhere, but is there some other reason why the effects aren't extensible?

**Comment by paf31** [comment]
I'd like to move to `Effect` as soon as it becomes viable (optimizations in the compiler and so on), but I used this for now with a closed effect row, since it was simple and covered enough of our use cases. Like you've seen, it's possible to work it with a coercion, but it's not ideal.
