### ISSUE TITLE
Why does `toReactComponent` return class components?

### ISSUE THREAD

**Issue by kl0tl** [lumihq/purescript-react-basic#90]
Is there a reason for `toReactComponent` to return a class component instead of a function?

PureScript terms can’t start with an uppercase but React (at least its v16.4.1) treats `<myPureScriptComponent />` as an HTML element and warns about its incorrect casing (it expects HTML elements names to be all lowercase), then complains about not recognizing the tag and doesn’t render anything.

This can be fixed by either renaming the component on import or rendering it with `React.createElement` instead of JSX syntax but returning a function instead of a class from `toReactComponent` would allow one to render `myPureScriptComponent` by calling it like a regular function (and could still be rendered with JSX syntax once renamed or `React.createElement`).

Also the class returned by `toReactComponent` silently doesn’t render anything when called like a function. If the component returned by `toReactComponent` must be a class could at least an error be thrown when its constructor is called without `new` (this can be inferred by checking if `!(this instanceof Component)`)? Both `React.createElement` and JSX syntax properly instantiate class components so this would warn against class components incorrectly called like functions and not rendering anything.

**Comment by justinwoo** [comment]
It's because `ReactComponent` is specifically meant to refer to a class component: https://pursuit.purescript.org/packages/purescript-react-basic/8.0.1/docs/React.Basic#t:ReactComponent

If you want something to use as a function, you should use `make`: https://pursuit.purescript.org/packages/purescript-react-basic/8.0.1/docs/React.Basic#v:make

But yes, when you import a component from PureScript, you need to give it a new name to use it with JSX.

**Comment by kl0tl** [comment]
Oh, I thought `ReactComponent` was there to refer to components imported from JavaScript or components exported for use in JavaScript (because the JavaScript props might differ from the ones one would like to work with in PureScript (`EffectFn2 a b Unit` vs `a -> b -> Effect Unit` for instance)).

**Comment by spicydonuts** [comment]
I think `ReactComponent` equally represents class and function components, but either way that means they should be used _as_ React components. That means applying `element` (or JSX syntax in JS) and not simply assuming it's a function to pass "props" into and calling it. The `react-basic-hooks` does create function components under the type `ReactComponent`.

The original issue of upper/lowercase syntax of JSX isn't really relevant to `react-basic` or PureScript. When you import the component into JS you can rename it:

```js
import { myPureScriptComponent as MyPureScriptComponent } from "..."
```

**Comment by spicydonuts** [comment]
It's also worth noting that `toReactComponent` _should_ have the type `_ -> _ -> _ -> Effect (ReactComponent _)`. Same with `createComponent`. They're not referentially transparent according to React's tree diffing algorithms. Probably something we'll address in the future, but yeah, just worth noting as another difference from just using a function.

**Comment by kl0tl** [comment]
I agree components shouldn’t be used as functions but they currently fail silently when they are, hence my suggestion to throw an error when they’re not. I’m introducing PureScript into a legacy app so the interop is really important to me and I’d like to help my coworkers avoid those mistakes.

I didn’t realize I don’t really need `toReactComponent` though. Is there any drawback to rendering a `props -> JSX` defined in PureScript like a regular React component in JavaScript (with JSX syntax or `React.createElement`)? It appears to work and I can’t think of any reason it wouldn‘t.

**Comment by spicydonuts** [comment]
It can work, you just need to make sure that function isn't getting rebuilt every time a render happens or it will unmount and rebuild the subtree.

**Comment by kl0tl** [comment]
Oh yes, didn’t thought of that. Thank you for your time 🙇

(Closing the issue since I got all I need to move forward.)
