### ISSUE TITLE
Missing commit in v9.0.1

### ISSUE THREAD

**Issue by kl0tl** [lumihq/purescript-react-basic#98]
The commit https://github.com/lumihq/purescript-react-basic/commit/3ca281e6dff3a0e7e142fd314b4451946787dd59 is nowhere to be found in the [v9.0.1](https://github.com/lumihq/purescript-react-basic/commits/v9.0.1) release. Was it intentional?

**Comment by hdgarrood** [comment]
Yes it was; that commit is a breaking change, so we'd have to make a major-level release (i.e. up to v10.0.0). The plan at the moment, as far as I'm aware, is to release a v10.0.0 including that change once #87 is in.
