### ISSUE TITLE
Should I expect removal of `SharedProps` to be included in the next release?

### ISSUE THREAD

**Issue by paluh** [lumihq/purescript-react-basic#99]
Hi,

as I'm working on some react libs bindings I wonder if I should expect `SharedProps` removal in the upcoming release - I mean this change: 3ca281e6dff3a0e7e142fd314b4451946787dd59 ?

If so I will work against master branch and just don't use them...

Thanks for building `react-basic`!

**Comment by spicydonuts** [comment]
Yes, I don’t think the changes in master will go away. There’s another open pr I wanted to merge before releasing but I haven’t had time to resolve the conflicts.

**Comment by paluh** [comment]
Thanks for clarification @spicydonuts !
